title:            周亨仓库
description:      个人博客，分享学习成果，记录个人生活
# put your disqus here
disqus_shortname: 
# put your duoshuo here
duoshuo:
  short_name: zhouheng

reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# When testing locally leave blank or use http://localhost:4000

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: '主页<br><small>Home</small>'
    url: '/'
  - title: '标签<br><small>Tag</small>'
    url: '/tags'
  - title: '托管<br><small>GitHub</small>'
    url: 'http://github.com/luzhouheng'
  - title: '关于我<br><small>About</small>'
    url: '/about/'
  - title: '分类<br><small>Categories</small>'
    url: '/categories'
    type: 'categories'
  - title: '网络艺术<br><small>Web Art</small>'
    url: '#'
    submenu:
      - title: 'Code Highlighter'
        url: '/intro/code-highlighting-post/'
      - title: 'Sample Post'
        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           卢周亨<br><small>luzhouheng</small>
  site:           http://www.zhouheng.asia
  avatar:         images/avatar.jpg
  bio:            "中国美术学院开放媒体系学生｜媒体艺术｜声音艺术｜职业抄代码<br>Student of Open Media Lab | Media Art | Sound Art | Coder"
  email:          peressio@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: luzhouheng # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: luzhouheng

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: luzhouheng

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/luzhouheng"
  - title: "vimeo"
    url: "https://vimeo.com/luzhouheng"
  - title: "twitter"
    url: "https://twitter.com/luzhouheng"
  - title: "facebook"
    url: "https://facebook.com/luzhouheng"
  - title: "tumblr"
    url: "https://artlinkzen.tumblr.com"
  - title: "zhihu"
    url: "https://www.zhihu.com/people/lu-zhou-heng"

# Image Path for Qiniu
IMG_PATH: http://7xrims.com1.z0.glb.clouddn.com

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-74684160-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    China/BEI_JING
locale:      zh-CN
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 8

# if true, shows the floatting share buttons
float_share: false


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "qrsync", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
